# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'boredom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Parse'
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.3'
  pod 'OAuthSwift'
  pod 'OAuthSwiftAlamofire'
  pod 'KeychainAccess'
  # Pods for boredom

  target 'boredomTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'boredomUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
