# Uncomment the next line to define a global platform for your project
#platform :ios, '10.0'

target 'boredom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Parse'
  
  pod 'AlamofireImage'
  pod 'OAuthSwift', '~> 1.2.0'
  pod 'KeychainAccess'
  pod 'SearchTextField'
  pod 'PopupDialog', '~> 0.7'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'

  # Promise function
  pod 'PromiseKit'


  # Pods for boredom

  target 'boredomTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'boredomUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
